Resolving MUI theme import error
When starting up the MUI-templated application with `yarn dev`, I received the following error:

TypeError: Cannot read property 'primary' of undefined
    at MyDocument.render (webpack-internal:///./src/pages/_document.tsx:35:73)

I believe this is due to an attempt to import the theme from `_app.tsx` without destructing the exported `theme` const